[pre-commit]
parallel = true

[pre-commit.commands.type-check]
run = "pnpm tsc --noEmit"
glob = "*.{ts,tsx}"
stage_fixed = true

[pre-commit.commands.style-guide]
run = "pnpm prettier --write {staged_files}"
glob = "*.{js,jsx,ts,tsx,md,json.css}"
stage_fixed = true

[pre-commit.commands.lint]
run = "next lint --fix --dir ."
stage_fixed = true