import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import type { ReactElement } from 'react';
import { PublicNav } from '@/ui/layout/public-nav';
import { validateRequest } from '@/lib/auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): Promise<ReactElement> {
  const { user } = await validateRequest();
  return (
    <html className="h-full" lang="en">
      <body className={`${inter.className} h-full bg-white`}>
        <PublicNav user={user} />
        <main className="py-24 sm:py-32">{children}</main>
      </body>
    </html>
  );
}
